export const copy = {
  live: {
    heading: "Live", refresh: "Refresh", loading: "Checking live status…",
    offline: "is not live right now.", failed: "Live status could not be loaded.",
    player: "TikTok live broadcast", unsupported: "Live playback is not supported in this browser. Try a current desktop Chrome or Edge.",
    disconnected: "The broadcast stopped or the connection was lost. Refresh to reconnect.",
    playHint: "Press play to watch with sound. Use the player controls for volume and fullscreen.",
    viewers: "viewers at last check", checked: "Checked", refreshHint: "Status refreshes on request (cached for 30 seconds).",
  },
  profile: {
    beforeSearch: "Search a username to see their profile and public content.",
    viewMore: "View more", loadingMore: "Loading more…",
    loadedAccounts: (loaded: number, total?: number) => total === undefined ? `${loaded} accounts loaded` : `${loaded} of ${total} accounts loaded`,
    partialAccounts: "The provider returned only part of this list. The profile total can include accounts it cannot retrieve.",
    accountLimit: "The current lookup limit is 240 accounts.",
    watch: "Watch here", closePlayer: "Close player",
    playerTitle: (title: string) => `TikTok player: ${title}`,
    playbackError: "This media couldn’t be played. Close the player and try again, or reload the section.",
    heading: "Explore this profile",
    sections: { posts: "Posts", reposts: "Reposts", highlights: "Collections", followers: "Followers", following: "Following" },
    likes: "Likes", stories: "Stories", load: "Load section", loading: "Loading this section…", retry: "Try again",
    prompt: "Choose a section to load public content from this account.",
    empty: "No content returned. This section may be empty or unavailable to the provider.",
    limited: "Showing up to 12 results returned by the provider.",
    experimental: "TikTok playlists and mixes shared by this account.",
    open: "Open on TikTok", untitled: "Untitled", back: "Back to collections", photo: "Post preview",
    unavailable: "—", posts: "Posts", collectionCount: (count: number) => `${count} posts`,
    errors: {
      PROFILE_INPUT: "Check the username and try again.",
      PROFILE_RESPONSE: "The provider returned an unsupported result. Please try again later.",
      PROFILE_UNAVAILABLE: "This section could not be retrieved. It may be restricted, empty, or temporarily unavailable.",
      PROFILE_CREDIT: "The provider requires paid credit for this request. Check your provider balance; free credit may not cover this endpoint.",
      PROFILE_RESTRICTED: "TikTok reports that this account is hiding this list.",
      PROFILE_ACCESS: "The provider could not authorize this request. Check the configured API key.",
      PROFILE_COLLECTION_EXPIRED: "This collection lookup has expired. Reload the Collections section.",
      PROFILE_BUSY: "Too many lookups are running. Please wait a minute and try again.",
    },
  },
  title: "TikTok Story Viewer",
  description: "Find currently available Stories from public TikTok accounts.",
  brand: "storyroom",
  brandLabel: "Storyroom home",
  intro: "Look up a public account. Watch their available Stories in one place.",
  label: "TikTok username",
  placeholder: "username",
  submit: "View Story",
  searching: "Finding Stories…",
  searchHint: "With or without @. Just the username, not a profile link.",
  footnote: "An independent viewer. Not affiliated with TikTok. Story availability is determined by the content provider.",
  viewerLabel: "Story viewer",
  readyTitle: "Your screen,\nready for a Story.",
  readyText: "Enter a username to start watching.",
  readyTag: "STORYROOM PLAYER",
  previewLabel: "Stories play here",
  previewHint: "Original format. Room to watch.",
  playLabel: "Play",
  pauseLabel: "Pause",
  loadingTitle: "Looking for the latest…",
  loadingText: "Checking for public Stories. This may take up to a minute.",
  emptyTitle: "No Stories returned",
  emptyText: "The provider returned no content. This does not confirm there is no public Story. Provider access or usage limits may also prevent retrieval.",
  errorTitle: "We couldn’t load that moment",
  retry: "Try again",
  previous: "Previous Story",
  next: "Next Story",
  play: "Play Story",
  pause: "Pause Story",
  mute: "Mute Story",
  unmute: "Unmute Story",
  volume: "Story volume",
  volumePercent: (value: number) => `${value}%`,
  replay: "Watch again",
  finished: "You’re all caught up",
  mediaError: "This media could not be loaded. The playback link may have stopped working. Retry playback or search again.",
  retryPlayback: "Retry playback",
  mediaAlt: "Story image",
  avatarAlt: "Profile photo",
  keyboardHint: "Tap left or right to navigate · Hold to pause",
  storyViews: (count: number) => `${new Intl.NumberFormat("en").format(count)} ${count === 1 ? "view" : "views"}`,
  progress: (index: number, total: number) => `Story ${index} of ${total}`,
  storyCount: (count: number) => `${count} ${count === 1 ? "Story" : "Stories"} available`,
  errors: {
    INVALID_USERNAME: "Enter a valid TikTok username: up to 24 letters, numbers, underscores or periods, with no period at the end.",
    NOT_CONFIGURED: "No API key is available for this request. Open API settings and save your KonbiniAPI key on this website.",
    KEY_SESSION_INVALID: "Your saved API key session expired or could not be read. Open API settings and save your key again. If this repeats, the site owner needs to check API_KEY_COOKIE_SECRET on this deployment.",
    PROVIDER_CREDIT: "KonbiniAPI credits are exhausted. Check the connected account balance.",
    PROVIDER_ERROR: "The Story provider is unavailable right now. Please try again later.",
    PROVIDER_RESPONSE_CHANGED: "The provider returned an unsupported response. Please try again later.",
    RATE_LIMITED: "Too many lookups right now. Please wait a minute and try again.",
    TIMEOUT: "The Story lookup took too long. Please try again later.",
    USER_NOT_FOUND: "This account could not be found. Check the username and try again.",
    PRIVATE_ACCOUNT: "Stories from private accounts are not available.",
    STORY_EXPIRED: "This Story has expired. Search again for newer Stories.",
    MEDIA_UNAVAILABLE: "A Story was found, but its media is unavailable.",
    NETWORK_ERROR: "Couldn’t connect. Check your connection and try again.",
  },
} as const;


